---
- hosts: webserver
  become: yes
  user: jenkins
  gather_facts: no
  connection: ssh
  tasks:
    - name: Install a Lynx pkg
      yum: name=lynx state=latest
    - name: Start a Lynx service
      service: name=lynx state=restarted
