---
- hosts: webserver
  become: yes
  user: jenkins
  gather_facts: no
  connection: ssh
  tasks:
    - name: Install a HTTPD pkg
      yum: name=httpd state=latest
    - name: Start a HTTPD service
      service: name=httpd state=restarted
    - name: insert/update HTML surrounded by custom markers after <body> line
      file:
        path: "/var/www/html/index.html"
        state: touch
        content: |
          Hello World...!
