---
- hosts: webserver
  gather_facts: no
  connection: ssh
  tasks:
    - name: Install a HTTPD pkg
      yum: name=httpd state=latest
    - name: Start a HTTPD service
      service: name=httpd state=restarted
